export {default as Home} from './HomePage'
export {default as About} from './AboutPage'
export {default as Contact} from './ContactPage'
export {default as Why} from './WhyPage'
export {default as NotFound} from './NotFound'